---
- hosts: localhost
  become: true
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
