---
- hosts: localhost
  become: true

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Apache2 web server
      apt:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Create HTML page
      copy:
        dest: /var/www/html/index.html
        content: "<h1>DevOps Practice Page – Setup by Ansible</h1>"
